
default:
	@echo "Make what? (all, libs, skeletons,  clean)"

all:
	(cd src ; make all)
#	(cd rep ; make all)

libs:
	(cd src ; make all)

skeletons:
	echo fixme
#	(cd rep ; make all)

clean:
	(cd src ; make clean)
#	(cd rep ; make clean)
